artifact_uri: /Users/vinu/Work/MLops/WaterMarkRemoval/mlartifacts/302715241102474404/11ec431b62bf453bada649a31c124fce/artifacts
end_time: 1775395666722
entry_point_name: ''
experiment_id: '302715241102474404'
lifecycle_stage: active
run_id: 11ec431b62bf453bada649a31c124fce
run_name: unique-steed-41
source_name: ''
source_type: 4
source_version: ''
start_time: 1775395637087
status: 3
tags: []
user_id: vinu
