artifact_uri: /Users/vinu/Work/MLops/WaterMarkRemoval/mlartifacts/302715241102474404/cbf50070729848b1a05fe8f0405b949b/artifacts
end_time: null
entry_point_name: ''
experiment_id: '302715241102474404'
lifecycle_stage: active
run_id: cbf50070729848b1a05fe8f0405b949b
run_name: victorious-shrike-99
source_name: ''
source_type: 4
source_version: ''
start_time: 1775410895654
status: 1
tags: []
user_id: vinu
